# Generated by Django 4.1.4 on 2023-01-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidates_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='position_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=20),
        ),
    ]
